/* Lógico projetos: */

CREATE TABLE DEPARTAMENTO (
    IDdepto VARCHAR PRIMARY KEY,
    nome VARCHAR,
    FK_EMPRESA_IDempresa VARCHAR
);

CREATE TABLE EMPRESA (
    IDempresa VARCHAR PRIMARY KEY,
    CNPJ VARCHAR,
    inscricao_estadual VARCHAR,
    razao_social VARCHAR
);

CREATE TABLE PROJETOS (
    IDprojeto VARCHAR PRIMARY KEY,
    descricao VARCHAR,
    localizacao VARCHAR
);

CREATE TABLE FUNCIONARIO (
    matricula VARCHAR PRIMARY KEY,
    nome VARCHAR,
    PIS VARCHAR,
    endereco VARCHAR,
    salario VARCHAR,
    sexo VARCHAR,
    data_nascimento VARCHAR,
    FK_DEPARTAMENTO_IDdepto VARCHAR
);

CREATE TABLE controle_projetos (
    fk_DEPARTAMENTO_IDdepto VARCHAR,
    fk_PROJETOS_IDprojeto VARCHAR,
    IDcontrole VARCHAR PRIMARY KEY
);

CREATE TABLE atua (
    fk_FUNCIONARIO_matricula VARCHAR,
    fk_PROJETOS_IDprojeto VARCHAR,
    horas VARCHAR,
    IDatuacao VARCHAR PRIMARY KEY
);
 
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_DEPARTAMENTO_2
    FOREIGN KEY (FK_EMPRESA_IDempresa)
    REFERENCES EMPRESA (IDempresa)
    ON DELETE RESTRICT;
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_2
    FOREIGN KEY (FK_DEPARTAMENTO_IDdepto)
    REFERENCES DEPARTAMENTO (IDdepto)
    ON DELETE RESTRICT;
 
ALTER TABLE controle_projetos ADD CONSTRAINT FK_controle_projetos_2
    FOREIGN KEY (fk_DEPARTAMENTO_IDdepto)
    REFERENCES DEPARTAMENTO (IDdepto)
    ON DELETE RESTRICT;
 
ALTER TABLE controle_projetos ADD CONSTRAINT FK_controle_projetos_3
    FOREIGN KEY (fk_PROJETOS_IDprojeto)
    REFERENCES PROJETOS (IDprojeto)
    ON DELETE SET NULL;
 
ALTER TABLE atua ADD CONSTRAINT FK_atua_2
    FOREIGN KEY (fk_FUNCIONARIO_matricula)
    REFERENCES FUNCIONARIO (matricula)
    ON DELETE RESTRICT;
 
ALTER TABLE atua ADD CONSTRAINT FK_atua_3
    FOREIGN KEY (fk_PROJETOS_IDprojeto)
    REFERENCES PROJETOS (IDprojeto)
    ON DELETE SET NULL;